import { DOMAIN_EVENTS, DomainEventType } from './domain-events';

export const EVENT_CATEGORIES = {
  SUBSCRIPTION: 'Subscription',
  PAYMENT: 'Payment',
  INVOICE: 'Invoice',
  WEBHOOK: 'Webhook',
  DUNNING: 'Dunning',
  NOTIFICATION: 'Notification',
  ANALYTICS: 'Analytics',
} as const;

export type EventCategory =
  (typeof EVENT_CATEGORIES)[keyof typeof EVENT_CATEGORIES];

const EVENT_CATEGORY_MAP: Record<DomainEventType, EventCategory> = {
  [DOMAIN_EVENTS.SUBSCRIPTION_CREATED]: EVENT_CATEGORIES.SUBSCRIPTION,
  [DOMAIN_EVENTS.SUBSCRIPTION_UPDATED]: EVENT_CATEGORIES.SUBSCRIPTION,
  [DOMAIN_EVENTS.SUBSCRIPTION_CANCELLED]: EVENT_CATEGORIES.SUBSCRIPTION,
  [DOMAIN_EVENTS.SUBSCRIPTION_RENEWED]: EVENT_CATEGORIES.SUBSCRIPTION,
  [DOMAIN_EVENTS.PAYMENT_FAILED]: EVENT_CATEGORIES.PAYMENT,
  [DOMAIN_EVENTS.PAYMENT_RECOVERED]: EVENT_CATEGORIES.PAYMENT,
  [DOMAIN_EVENTS.PAYMENT_STARTED]: EVENT_CATEGORIES.PAYMENT,
  [DOMAIN_EVENTS.INVOICE_PAID]: EVENT_CATEGORIES.INVOICE,
  [DOMAIN_EVENTS.INVOICE_GENERATED]: EVENT_CATEGORIES.INVOICE,
  [DOMAIN_EVENTS.RETRY_SCHEDULED]: EVENT_CATEGORIES.DUNNING,
  [DOMAIN_EVENTS.WEBHOOK_SENT]: EVENT_CATEGORIES.WEBHOOK,
  [DOMAIN_EVENTS.CHAOS_SCENARIO_STARTED]: EVENT_CATEGORIES.ANALYTICS,
};

export function resolveEventCategory(eventType: string): EventCategory {
  return (
    EVENT_CATEGORY_MAP[eventType as DomainEventType] ??
    EVENT_CATEGORIES.ANALYTICS
  );
}
